os: linux
language: node_js
script:
  - npm run lint
deploy:
  provider: heroku
  app: powerful-harbor-93786
  strategy: git
  on:
    repo: lyne-design-system/lyne-figma-listener
  api_key: $HEROKU_TOKEN
