os: linux
language: node_js
script:
  - npm run lint
deploy:
  provider: heroku
  app: powerful-harbor-93786
  strategy: git
  api_key:
    secure: qA50VnsldKbblx0ZyZp2IgfwTPe6bdFgSKXer/wwiZVx2F1BL9R4cK4W0IPt5fS488zwmEc0M64RxQaHGwx/mQEafdnuOgYQzDEK19f2mCn9Ev11OqaA+04lDhIf0rO3DXJBmzBGffHsZ/ABlUDpDe7xvNM2Ehk7XixBNzqJEtr3dYT2rvBg28XxeDFSZ1vebZ5fpsfkziYJzMJ+25z1vohbBmYGiHTkabuPK+Hhn56FZKhlis6fJ6UukTiaHTmDB5eyVQ3+yMWpqihPXReV8SXOalByKAZKWICy1XJibNMX0t1LIPLOXuGZdaOEFzmyiERz8i2puHog/DKRFZQfBAXleC7PIHDEwgGo+KGNGQm0ZRxm/xXCjPwJCPzxHneGz9xvhWahzjgzRcmW4gU5C87f/gKJbi2DUWnR8QRP5LfOUCJgY27SNET1y65M4Dgi8ydOH9hQXtKCSc63bCBDkqSOPpthvNpFrX+NfgyzlhUALk8LbCXCiQvkZ/u2nZYDzwBqIj8FAEvVTqydIMAEYM84c6QBnBt+NsrBwt4PoQMhIDg7em3O+wvYRwo+SwoyP1BXEv/4FIfMTQd7W3gEQFa8KgPSQWIEUAObvvuo32AUc/2mCJM5nLJSOVBrofySY2U8tKdoW3Utie0h4rZi60uxbWBwNpzqQpWNEb4LNhg=
